name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  DEPLOY_USER: deployer
  DEPLOY_PATH: /var/www/sarthaksinghgaur.me/sarthaksinghgaur.github.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            
            # Pull latest changes
            git fetch origin
            git reset --hard origin/main
            
            # Activate virtual environment
            source venv/bin/activate
            
            # Install/update dependencies
            pip install -r requirements.txt
            
            
            # Restart the service (using sudo with limited permissions)
            sudo systemctl restart resume-portfolio.service
            
            # Check service status
            sudo systemctl status resume-portfolio.service
