name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
  DEPLOY_USER: deployer
  DEPLOY_PATH: /var/www/sarthaksinghgaur.me/sarthaksinghgaur.github.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
          
      - name: Deploy to server
        run: |
          # Create a temporary deployment script
          cat > deploy.sh << 'EOF'
          #!/bin/bash
          set -e
          
          # Ensure we're in the correct directory
          cd ${{ env.DEPLOY_PATH }}
          
          # Pull latest changes
          git fetch origin
          git reset --hard origin/main
          
          # Activate virtual environment
          source venv/bin/activate
          
          # Install/update dependencies
          pip install -r requirements.txt
          
          # Set proper permissions
          sudo chown -R www-data:www-data .
          sudo chmod -R g+rw .
          
          # Restart the service (using sudo with limited permissions)
          sudo systemctl restart resume-portfolio.service
          
          # Check service status
          sudo systemctl status resume-portfolio.service
          EOF
          
          # Make script executable
          chmod +x deploy.sh
          
          # Execute deployment script on server
          ssh -o StrictHostKeyChecking=no ${{ env.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd ${{ env.DEPLOY_PATH }} && ./deploy.sh"
